module.exports = {
	proxies: [],
	'proxy-groups': [],
	rules: [
		"DOMAIN-SUFFIX,google.cn,DIRECT",
		'DOMAIN-KEYWORD,admarvel,REJECT',
		'DOMAIN-KEYWORD,admaster,REJECT',
		'DOMAIN-KEYWORD,adsage,REJECT',
		'DOMAIN-KEYWORD,adsmogo,REJECT',
		'DOMAIN-KEYWORD,adsrvmedia,REJECT',
		'DOMAIN-KEYWORD,adwords,REJECT',
		'DOMAIN-KEYWORD,adservice,REJECT',
		'DOMAIN-KEYWORD,domob,REJECT',
		'DOMAIN-KEYWORD,duomeng,REJECT',
		'DOMAIN-KEYWORD,dwtrack,REJECT',
		'DOMAIN-KEYWORD,guanggao,REJECT',
		'DOMAIN-KEYWORD,lianmeng,REJECT',
		'DOMAIN-KEYWORD,omgmta,REJECT',
		'DOMAIN-KEYWORD,openx,REJECT',
		'DOMAIN-KEYWORD,partnerad,REJECT',
		'DOMAIN-KEYWORD,pingfore,REJECT',
		'DOMAIN-KEYWORD,supersonicads,REJECT',
		'DOMAIN-KEYWORD,tracking,REJECT',
		'DOMAIN-KEYWORD,uedas,REJECT',
		'DOMAIN-KEYWORD,umeng,REJECT',
		'DOMAIN-KEYWORD,usage,REJECT',
		'DOMAIN-KEYWORD,wlmonitor,REJECT',
		'DOMAIN-KEYWORD,zjtoolbar,REJECT',
		'DOMAIN-KEYWORD,n3ro,REJECT',
		'DOMAIN-KEYWORD,sy168,REJECT',
		'DOMAIN-KEYWORD,space,REJECT',
		'DOMAIN-KEYWORD,china-cdn-net,REJECT',
		'DOMAIN-KEYWORD,gacloudltd,REJECT',
		'DOMAIN-KEYWORD,cylink,REJECT',
		'DOMAIN-KEYWORD,as64271,REJECT',
		'DOMAIN-KEYWORD,hitun,REJECT',
		'DOMAIN-KEYWORD,jike0001,REJECT',
		"DOMAIN-SUFFIX,ampproject.org,🎯 节点选择",
		"DOMAIN-SUFFIX,appspot.com,🎯 节点选择",
		"DOMAIN-SUFFIX,blogger.com,🎯 节点选择",
		"DOMAIN-SUFFIX,getoutline.org,🎯 节点选择",
		"DOMAIN-SUFFIX,gvt0.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gvt1.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gvt3.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🎯 节点选择",
		"DOMAIN-KEYWORD,google,🎯 节点选择",
		"DOMAIN-KEYWORD,blogspot,🎯 节点选择",
		"DOMAIN-SUFFIX,onedrive.live.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xboxlive.com,🎯 节点选择",
		"DOMAIN-SUFFIX,cdninstagram.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fb.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fb.me,🎯 节点选择",
		"DOMAIN-SUFFIX,fbaddins.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fbcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,fbsbx.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fbworkmail.com,🎯 节点选择",
		"DOMAIN-SUFFIX,instagram.com,🎯 节点选择",
		"DOMAIN-SUFFIX,m.me,🎯 节点选择",
		"DOMAIN-SUFFIX,messenger.com,🎯 节点选择",
		"DOMAIN-SUFFIX,oculus.com,🎯 节点选择",
		"DOMAIN-SUFFIX,oculuscdn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,rocksdb.org,🎯 节点选择",
		"DOMAIN-SUFFIX,whatsapp.com,🎯 节点选择",
		"DOMAIN-SUFFIX,whatsapp.net,🎯 节点选择",
		"DOMAIN-KEYWORD,facebook,🎯 节点选择",
		"IP-CIDR,3.123.36.126/32,🎯 节点选择,no-resolve",
		"IP-CIDR,35.157.215.84/32,🎯 节点选择,no-resolve",
		"IP-CIDR,35.157.217.255/32,🎯 节点选择,no-resolve",
		"IP-CIDR,52.58.209.134/32,🎯 节点选择,no-resolve",
		"IP-CIDR,54.93.124.31/32,🎯 节点选择,no-resolve",
		"IP-CIDR,54.162.243.80/32,🎯 节点选择,no-resolve",
		"IP-CIDR,54.173.34.141/32,🎯 节点选择,no-resolve",
		"IP-CIDR,54.235.23.242/32,🎯 节点选择,no-resolve",
		"IP-CIDR,169.45.248.118/32,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,pscp.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,periscope.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,t.co,🎯 节点选择",
		"DOMAIN-SUFFIX,twimg.co,🎯 节点选择",
		"DOMAIN-SUFFIX,twimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,twitpic.com,🎯 节点选择",
		"DOMAIN-SUFFIX,vine.co,🎯 节点选择",
		"DOMAIN-KEYWORD,twitter,🎯 节点选择",
		"DOMAIN-SUFFIX,t.me,🎯 节点选择",
		"DOMAIN-SUFFIX,tdesktop.com,🎯 节点选择",
		"DOMAIN-SUFFIX,telegra.ph,🎯 节点选择",
		"DOMAIN-SUFFIX,telegram.me,🎯 节点选择",
		"DOMAIN-SUFFIX,telegram.org,🎯 节点选择",
		"IP-CIDR,91.108.4.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.8.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.12.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.16.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.56.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,149.154.160.0/20,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:b28:f23d::/48,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:b28:f23f::/48,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:67c:4e8::/48,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,line.me,🎯 节点选择",
		"DOMAIN-SUFFIX,line-apps.com,🎯 节点选择",
		"DOMAIN-SUFFIX,line-scdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,naver.jp,🎯 节点选择",
		"IP-CIDR,103.2.30.0/23,🎯 节点选择,no-resolve",
		"IP-CIDR,125.209.208.0/20,🎯 节点选择,no-resolve",
		"IP-CIDR,147.92.128.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,203.104.144.0/21,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,4shared.com,🎯 节点选择",
		"DOMAIN-SUFFIX,520cc.cc,🎯 节点选择",
		"DOMAIN-SUFFIX,881903.com,🎯 节点选择",
		"DOMAIN-SUFFIX,9cache.com,🎯 节点选择",
		"DOMAIN-SUFFIX,9gag.com,🎯 节点选择",
		"DOMAIN-SUFFIX,abc.com,🎯 节点选择",
		"DOMAIN-SUFFIX,abc.net.au,🎯 节点选择",
		"DOMAIN-SUFFIX,abebooks.com,🎯 节点选择",
		"DOMAIN-SUFFIX,amazon.co.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,apigee.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apk-dl.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apkfind.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apkmirror.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apkmonk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apkpure.com,🎯 节点选择",
		"DOMAIN-SUFFIX,aptoide.com,🎯 节点选择",
		"DOMAIN-SUFFIX,archive.is,🎯 节点选择",
		"DOMAIN-SUFFIX,archive.org,🎯 节点选择",
		"DOMAIN-SUFFIX,arte.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,artstation.com,🎯 节点选择",
		"DOMAIN-SUFFIX,arukas.io,🎯 节点选择",
		"DOMAIN-SUFFIX,ask.com,🎯 节点选择",
		"DOMAIN-SUFFIX,avg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,avgle.com,🎯 节点选择",
		"DOMAIN-SUFFIX,badoo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bandwagonhost.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bbc.com,🎯 节点选择",
		"DOMAIN-SUFFIX,behance.net,🎯 节点选择",
		"DOMAIN-SUFFIX,bibox.com,🎯 节点选择",
		"DOMAIN-SUFFIX,biggo.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,binance.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bitcointalk.org,🎯 节点选择",
		"DOMAIN-SUFFIX,bitfinex.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bitmex.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bit-z.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bloglovin.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bloomberg.cn,🎯 节点选择",
		"DOMAIN-SUFFIX,bloomberg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,blubrry.com,🎯 节点选择",
		"DOMAIN-SUFFIX,book.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,booklive.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,books.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,boslife.net,🎯 节点选择",
		"DOMAIN-SUFFIX,box.com,🎯 节点选择",
		"DOMAIN-SUFFIX,businessinsider.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bwh1.net,🎯 节点选择",
		"DOMAIN-SUFFIX,castbox.fm,🎯 节点选择",
		"DOMAIN-SUFFIX,cbc.ca,🎯 节点选择",
		"DOMAIN-SUFFIX,cdw.com,🎯 节点选择",
		"DOMAIN-SUFFIX,change.org,🎯 节点选择",
		"DOMAIN-SUFFIX,channelnewsasia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ck101.com,🎯 节点选择",
		"DOMAIN-SUFFIX,clarionproject.org,🎯 节点选择",
		"DOMAIN-SUFFIX,clyp.it,🎯 节点选择",
		"DOMAIN-SUFFIX,cna.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,comparitech.com,🎯 节点选择",
		"DOMAIN-SUFFIX,conoha.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,crucial.com,🎯 节点选择",
		"DOMAIN-SUFFIX,cts.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,cw.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,cyberctm.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dailymotion.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dailyview.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,daum.net,🎯 节点选择",
		"DOMAIN-SUFFIX,daumcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,dcard.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,deepdiscount.com,🎯 节点选择",
		"DOMAIN-SUFFIX,depositphotos.com,🎯 节点选择",
		"DOMAIN-SUFFIX,deviantart.com,🎯 节点选择",
		"DOMAIN-SUFFIX,disconnect.me,🎯 节点选择",
		"DOMAIN-SUFFIX,discordapp.com,🎯 节点选择",
		"DOMAIN-SUFFIX,discordapp.net,🎯 节点选择",
		"DOMAIN-SUFFIX,disqus.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dlercloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dns2go.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dowjones.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dropbox.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dropboxusercontent.com,🎯 节点选择",
		"DOMAIN-SUFFIX,duckduckgo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dw.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dynu.com,🎯 节点选择",
		"DOMAIN-SUFFIX,earthcam.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ebookservice.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,economist.com,🎯 节点选择",
		"DOMAIN-SUFFIX,edgecastcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,edu,🎯 节点选择",
		"DOMAIN-SUFFIX,elpais.com,🎯 节点选择",
		"DOMAIN-SUFFIX,enanyang.my,🎯 节点选择",
		"DOMAIN-SUFFIX,encyclopedia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,esoir.be,🎯 节点选择",
		"DOMAIN-SUFFIX,etherscan.io,🎯 节点选择",
		"DOMAIN-SUFFIX,euronews.com,🎯 节点选择",
		"DOMAIN-SUFFIX,evozi.com,🎯 节点选择",
		"DOMAIN-SUFFIX,feedly.com,🎯 节点选择",
		"DOMAIN-SUFFIX,firech.at,🎯 节点选择",
		"DOMAIN-SUFFIX,flickr.com,🎯 节点选择",
		"DOMAIN-SUFFIX,flitto.com,🎯 节点选择",
		"DOMAIN-SUFFIX,foreignpolicy.com,🎯 节点选择",
		"DOMAIN-SUFFIX,freebrowser.org,🎯 节点选择",
		"DOMAIN-SUFFIX,freewechat.com,🎯 节点选择",
		"DOMAIN-SUFFIX,freeweibo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,friday.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,ftchinese.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ftimg.net,🎯 节点选择",
		"DOMAIN-SUFFIX,gate.io,🎯 节点选择",
		"DOMAIN-SUFFIX,getlantern.org,🎯 节点选择",
		"DOMAIN-SUFFIX,getsync.com,🎯 节点选择",
		"DOMAIN-SUFFIX,globalvoices.org,🎯 节点选择",
		"DOMAIN-SUFFIX,goo.ne.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,goodreads.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gov,🎯 节点选择",
		"DOMAIN-SUFFIX,gov.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,greatfire.org,🎯 节点选择",
		"DOMAIN-SUFFIX,gumroad.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,heroku.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hightail.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hk01.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hkbf.org,🎯 节点选择",
		"DOMAIN-SUFFIX,hkbookcity.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hkej.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hket.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hkgolden.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hootsuite.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hudson.org,🎯 节点选择",
		"DOMAIN-SUFFIX,hyread.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,ibtimes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,i-cable.com,🎯 节点选择",
		"DOMAIN-SUFFIX,icij.org,🎯 节点选择",
		"DOMAIN-SUFFIX,icoco.com,🎯 节点选择",
		"DOMAIN-SUFFIX,imgur.com,🎯 节点选择",
		"DOMAIN-SUFFIX,initiummall.com,🎯 节点选择",
		"DOMAIN-SUFFIX,insecam.org,🎯 节点选择",
		"DOMAIN-SUFFIX,ipfs.io,🎯 节点选择",
		"DOMAIN-SUFFIX,issuu.com,🎯 节点选择",
		"DOMAIN-SUFFIX,istockphoto.com,🎯 节点选择",
		"DOMAIN-SUFFIX,japantimes.co.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,jiji.com,🎯 节点选择",
		"DOMAIN-SUFFIX,jinx.com,🎯 节点选择",
		"DOMAIN-SUFFIX,jkforum.net,🎯 节点选择",
		"DOMAIN-SUFFIX,joinmastodon.org,🎯 节点选择",
		"DOMAIN-SUFFIX,justmysocks.net,🎯 节点选择",
		"DOMAIN-SUFFIX,justpaste.it,🎯 节点选择",
		"DOMAIN-SUFFIX,kakao.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kakaocorp.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kik.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kobo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kobobooks.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kodingen.com,🎯 节点选择",
		"DOMAIN-SUFFIX,lemonde.fr,🎯 节点选择",
		"DOMAIN-SUFFIX,lepoint.fr,🎯 节点选择",
		"DOMAIN-SUFFIX,lihkg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,linkedin.com,🎯 节点选择",
		"DOMAIN-SUFFIX,listennotes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,livestream.com,🎯 节点选择",
		"DOMAIN-SUFFIX,logmein.com,🎯 节点选择",
		"DOMAIN-SUFFIX,mail.ru,🎯 节点选择",
		"DOMAIN-SUFFIX,mailchimp.com,🎯 节点选择",
		"DOMAIN-SUFFIX,marc.info,🎯 节点选择",
		"DOMAIN-SUFFIX,matters.news,🎯 节点选择",
		"DOMAIN-SUFFIX,maying.co,🎯 节点选择",
		"DOMAIN-SUFFIX,medium.com,🎯 节点选择",
		"DOMAIN-SUFFIX,mega.nz,🎯 节点选择",
		"DOMAIN-SUFFIX,mil,🎯 节点选择",
		"DOMAIN-SUFFIX,mingpao.com,🎯 节点选择",
		"DOMAIN-SUFFIX,mobile01.com,🎯 节点选择",
		"DOMAIN-SUFFIX,myspace.com,🎯 节点选择",
		"DOMAIN-SUFFIX,myspacecdn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nanyang.com,🎯 节点选择",
		"DOMAIN-SUFFIX,naver.com,🎯 节点选择",
		"DOMAIN-SUFFIX,neowin.net,🎯 节点选择",
		"DOMAIN-SUFFIX,newstapa.org,🎯 节点选择",
		"DOMAIN-SUFFIX,nexitally.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nhk.or.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,nicovideo.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,nii.ac.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,nikkei.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nofile.io,🎯 节点选择",
		"DOMAIN-SUFFIX,now.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nrk.no,🎯 节点选择",
		"DOMAIN-SUFFIX,nyt.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytchina.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytcn.me,🎯 节点选择",
		"DOMAIN-SUFFIX,nytco.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytimes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytlog.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nytstyle.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ok.ru,🎯 节点选择",
		"DOMAIN-SUFFIX,okex.com,🎯 节点选择",
		"DOMAIN-SUFFIX,on.cc,🎯 节点选择",
		"DOMAIN-SUFFIX,orientaldaily.com.my,🎯 节点选择",
		"DOMAIN-SUFFIX,overcast.fm,🎯 节点选择",
		"DOMAIN-SUFFIX,paltalk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pao-pao.net,🎯 节点选择",
		"DOMAIN-SUFFIX,parsevideo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pbxes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pcdvd.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,pchome.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,pcloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,picacomic.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pinimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pixiv.net,🎯 节点选择",
		"DOMAIN-SUFFIX,player.fm,🎯 节点选择",
		"DOMAIN-SUFFIX,plurk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,po18.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,potato.im,🎯 节点选择",
		"DOMAIN-SUFFIX,potatso.com,🎯 节点选择",
		"DOMAIN-SUFFIX,prism-break.org,🎯 节点选择",
		"DOMAIN-SUFFIX,proxifier.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pt.im,🎯 节点选择",
		"DOMAIN-SUFFIX,pts.org.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,pubu.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,pubu.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,pureapk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,quora.com,🎯 节点选择",
		"DOMAIN-SUFFIX,quoracdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,rakuten.co.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,readingtimes.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,readmoo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,redbubble.com,🎯 节点选择",
		"DOMAIN-SUFFIX,reddit.com,🎯 节点选择",
		"DOMAIN-SUFFIX,redditmedia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,resilio.com,🎯 节点选择",
		"DOMAIN-SUFFIX,reuters.com,🎯 节点选择",
		"DOMAIN-SUFFIX,reutersmedia.net,🎯 节点选择",
		"DOMAIN-SUFFIX,rfi.fr,🎯 节点选择",
		"DOMAIN-SUFFIX,rixcloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,roadshow.hk,🎯 节点选择",
		"DOMAIN-SUFFIX,scmp.com,🎯 节点选择",
		"DOMAIN-SUFFIX,scribd.com,🎯 节点选择",
		"DOMAIN-SUFFIX,seatguru.com,🎯 节点选择",
		"DOMAIN-SUFFIX,shadowsocks.org,🎯 节点选择",
		"DOMAIN-SUFFIX,shopee.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,slideshare.net,🎯 节点选择",
		"DOMAIN-SUFFIX,softfamous.com,🎯 节点选择",
		"DOMAIN-SUFFIX,soundcloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ssrcloud.org,🎯 节点选择",
		"DOMAIN-SUFFIX,startpage.com,🎯 节点选择",
		"DOMAIN-SUFFIX,steamcommunity.com,🎯 节点选择",
		"DOMAIN-SUFFIX,steemit.com,🎯 节点选择",
		"DOMAIN-SUFFIX,steemitwallet.com,🎯 节点选择",
		"DOMAIN-SUFFIX,t66y.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tapatalk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,teco-hk.org,🎯 节点选择",
		"DOMAIN-SUFFIX,teco-mo.org,🎯 节点选择",
		"DOMAIN-SUFFIX,teddysun.com,🎯 节点选择",
		"DOMAIN-SUFFIX,textnow.me,🎯 节点选择",
		"DOMAIN-SUFFIX,theguardian.com,🎯 节点选择",
		"DOMAIN-SUFFIX,theinitium.com,🎯 节点选择",
		"DOMAIN-SUFFIX,thetvdb.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tineye.com,🎯 节点选择",
		"DOMAIN-SUFFIX,torproject.org,🎯 节点选择",
		"DOMAIN-SUFFIX,tumblr.com,🎯 节点选择",
		"DOMAIN-SUFFIX,turbobit.net,🎯 节点选择",
		"DOMAIN-SUFFIX,tutanota.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tvboxnow.com,🎯 节点选择",
		"DOMAIN-SUFFIX,udn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,unseen.is,🎯 节点选择",
		"DOMAIN-SUFFIX,upmedia.mg,🎯 节点选择",
		"DOMAIN-SUFFIX,uptodown.com,🎯 节点选择",
		"DOMAIN-SUFFIX,urbandictionary.com,🎯 节点选择",
		"DOMAIN-SUFFIX,ustream.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,uwants.com,🎯 节点选择",
		"DOMAIN-SUFFIX,v2ray.com,🎯 节点选择",
		"DOMAIN-SUFFIX,viber.com,🎯 节点选择",
		"DOMAIN-SUFFIX,videopress.com,🎯 节点选择",
		"DOMAIN-SUFFIX,vimeo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,voachinese.com,🎯 节点选择",
		"DOMAIN-SUFFIX,voanews.com,🎯 节点选择",
		"DOMAIN-SUFFIX,voxer.com,🎯 节点选择",
		"DOMAIN-SUFFIX,vzw.com,🎯 节点选择",
		"DOMAIN-SUFFIX,w3schools.com,🎯 节点选择",
		"DOMAIN-SUFFIX,washingtonpost.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wattpad.com,🎯 节点选择",
		"DOMAIN-SUFFIX,whoer.net,🎯 节点选择",
		"DOMAIN-SUFFIX,wikimapia.org,🎯 节点选择",
		"DOMAIN-SUFFIX,wikipedia.org,🎯 节点选择",
		"DOMAIN-SUFFIX,wikiquote.org,🎯 节点选择",
		"DOMAIN-SUFFIX,wikiwand.com,🎯 节点选择",
		"DOMAIN-SUFFIX,winudf.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wire.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wordpress.com,🎯 节点选择",
		"DOMAIN-SUFFIX,workflow.is,🎯 节点选择",
		"DOMAIN-SUFFIX,worldcat.org,🎯 节点选择",
		"DOMAIN-SUFFIX,wsj.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wsj.net,🎯 节点选择",
		"DOMAIN-SUFFIX,xhamster.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xn--90wwvt03e.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xn--i2ru8q2qg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xnxx.com,🎯 节点选择",
		"DOMAIN-SUFFIX,xvideos.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yahoo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yandex.ru,🎯 节点选择",
		"DOMAIN-SUFFIX,ycombinator.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yesasia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yes-news.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yomiuri.co.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,you-get.org,🎯 节点选择",
		"DOMAIN-SUFFIX,zaobao.com,🎯 节点选择",
		"DOMAIN-SUFFIX,zb.com,🎯 节点选择",
		"DOMAIN-SUFFIX,zello.com,🎯 节点选择",
		"DOMAIN-SUFFIX,zeronet.io,🎯 节点选择",
		"DOMAIN-SUFFIX,zoom.us,🎯 节点选择",
		"DOMAIN-KEYWORD,github,🎯 节点选择",
		"DOMAIN-KEYWORD,jav,🎯 节点选择",
		"DOMAIN-KEYWORD,pinterest,🎯 节点选择",
		"DOMAIN-KEYWORD,porn,🎯 节点选择",
		"DOMAIN-KEYWORD,wikileaks,🎯 节点选择",
		"DOMAIN-SUFFIX,apartmentratings.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apartments.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bankmobilevibe.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bing.com,🎯 节点选择",
		"DOMAIN-SUFFIX,booktopia.com.au,🎯 节点选择",
		"DOMAIN-SUFFIX,cccat.io,🎯 节点选择",
		"DOMAIN-SUFFIX,centauro.com.br,🎯 节点选择",
		"DOMAIN-SUFFIX,clearsurance.com,🎯 节点选择",
		"DOMAIN-SUFFIX,costco.com,🎯 节点选择",
		"DOMAIN-SUFFIX,crackle.com,🎯 节点选择",
		"DOMAIN-SUFFIX,depositphotos.cn,🎯 节点选择",
		"DOMAIN-SUFFIX,dish.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dmm.co.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,dmm.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dnvod.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,esurance.com,🎯 节点选择",
		"DOMAIN-SUFFIX,extmatrix.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fastpic.ru,🎯 节点选择",
		"DOMAIN-SUFFIX,flipboard.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fnac.be,🎯 节点选择",
		"DOMAIN-SUFFIX,fnac.com,🎯 节点选择",
		"DOMAIN-SUFFIX,funkyimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,fxnetworks.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gettyimages.com,🎯 节点选择",
		"DOMAIN-SUFFIX,go.com,🎯 节点选择",
		"DOMAIN-SUFFIX,here.com,🎯 节点选择",
		"DOMAIN-SUFFIX,jcpenney.com,🎯 节点选择",
		"DOMAIN-SUFFIX,jiehua.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,mailfence.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nationwide.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nbc.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nexon.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nordstrom.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nordstromimage.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nordstromrack.com,🎯 节点选择",
		"DOMAIN-SUFFIX,superpages.com,🎯 节点选择",
		"DOMAIN-SUFFIX,target.com,🎯 节点选择",
		"DOMAIN-SUFFIX,thinkgeek.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tracfone.com,🎯 节点选择",
		"DOMAIN-SUFFIX,unity3d.com,🎯 节点选择",
		"DOMAIN-SUFFIX,uploader.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,vevo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,viu.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,vk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,vsco.co,🎯 节点选择",
		"DOMAIN-SUFFIX,xfinity.com,🎯 节点选择",
		"DOMAIN-SUFFIX,zattoo.com,🎯 节点选择",
		"DOMAIN,testflight.apple.com,🎯 节点选择",
		"DOMAIN-SUFFIX,appsto.re,🎯 节点选择",
		"DOMAIN,books.itunes.apple.com,🎯 节点选择",
		"DOMAIN,hls.itunes.apple.com,🎯 节点选择",
		"DOMAIN,apps.apple.com,🎯 节点选择",
		"DOMAIN,itunes.apple.com,🎯 节点选择",
		"DOMAIN,api-glb-sea.smoot.apple.com,🎯 节点选择",
		"DOMAIN,lookup-api.apple.com,🎯 节点选择",
		"DOMAIN-SUFFIX,abc.xyz,🎯 节点选择",
		"DOMAIN-SUFFIX,android.com,🎯 节点选择",
		"DOMAIN-SUFFIX,androidify.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dialogflow.com,🎯 节点选择",
		"DOMAIN-SUFFIX,autodraw.com,🎯 节点选择",
		"DOMAIN-SUFFIX,capitalg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,certificate-transparency.org,🎯 节点选择",
		"DOMAIN-SUFFIX,chrome.com,🎯 节点选择",
		"DOMAIN-SUFFIX,chromeexperiments.com,🎯 节点选择",
		"DOMAIN-SUFFIX,chromestatus.com,🎯 节点选择",
		"DOMAIN-SUFFIX,chromium.org,🎯 节点选择",
		"DOMAIN-SUFFIX,creativelab5.com,🎯 节点选择",
		"DOMAIN-SUFFIX,debug.com,🎯 节点选择",
		"DOMAIN-SUFFIX,deepmind.com,🎯 节点选择",
		"DOMAIN-SUFFIX,firebaseio.com,🎯 节点选择",
		"DOMAIN-SUFFIX,getmdl.io,🎯 节点选择",
		"DOMAIN-SUFFIX,ggpht.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gmail.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gmodules.com,🎯 节点选择",
		"DOMAIN-SUFFIX,godoc.org,🎯 节点选择",
		"DOMAIN-SUFFIX,golang.org,🎯 节点选择",
		"DOMAIN-SUFFIX,gv.com,🎯 节点选择",
		"DOMAIN-SUFFIX,gwtproject.org,🎯 节点选择",
		"DOMAIN-SUFFIX,itasoftware.com,🎯 节点选择",
		"DOMAIN-SUFFIX,madewithcode.com,🎯 节点选择",
		"DOMAIN-SUFFIX,material.io,🎯 节点选择",
		"DOMAIN-SUFFIX,polymer-project.org,🎯 节点选择",
		"DOMAIN-SUFFIX,admin.recaptcha.net,🎯 节点选择",
		"DOMAIN-SUFFIX,recaptcha.net,🎯 节点选择",
		"DOMAIN-SUFFIX,shattered.io,🎯 节点选择",
		"DOMAIN-SUFFIX,synergyse.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tensorflow.org,🎯 节点选择",
		"DOMAIN-SUFFIX,tfhub.dev,🎯 节点选择",
		"DOMAIN-SUFFIX,tiltbrush.com,🎯 节点选择",
		"DOMAIN-SUFFIX,waveprotocol.org,🎯 节点选择",
		"DOMAIN-SUFFIX,waymo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,webmproject.org,🎯 节点选择",
		"DOMAIN-SUFFIX,webrtc.org,🎯 节点选择",
		"DOMAIN-SUFFIX,whatbrowser.org,🎯 节点选择",
		"DOMAIN-SUFFIX,widevine.com,🎯 节点选择",
		"DOMAIN-SUFFIX,x.company,🎯 节点选择",
		"DOMAIN-SUFFIX,youtu.be,🎯 节点选择",
		"DOMAIN-SUFFIX,yt.be,🎯 节点选择",
		"DOMAIN-SUFFIX,ytimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,1drv.com,🎯 节点选择",
		"DOMAIN-SUFFIX,1drv.ms,🎯 节点选择",
		"DOMAIN-SUFFIX,blob.core.windows.net,🎯 节点选择",
		"DOMAIN-SUFFIX,livefilestore.com,🎯 节点选择",
		"DOMAIN-SUFFIX,onedrive.com,🎯 节点选择",
		"DOMAIN-SUFFIX,storage.live.com,🎯 节点选择",
		"DOMAIN-SUFFIX,storage.msn.com,🎯 节点选择",
		"DOMAIN,oneclient.sfx.ms,🎯 节点选择",
		"DOMAIN-SUFFIX,0rz.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,4bluestones.biz,🎯 节点选择",
		"DOMAIN-SUFFIX,9bis.net,🎯 节点选择",
		"DOMAIN-SUFFIX,allconnected.co,🎯 节点选择",
		"DOMAIN-SUFFIX,aol.com,🎯 节点选择",
		"DOMAIN-SUFFIX,bcc.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,bit.ly,🎯 节点选择",
		"DOMAIN-SUFFIX,bitshare.com,🎯 节点选择",
		"DOMAIN-SUFFIX,blog.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,blogimg.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,blogtd.org,🎯 节点选择",
		"DOMAIN-SUFFIX,broadcast.co.nz,🎯 节点选择",
		"DOMAIN-SUFFIX,camfrog.com,🎯 节点选择",
		"DOMAIN-SUFFIX,cfos.de,🎯 节点选择",
		"DOMAIN-SUFFIX,citypopulation.de,🎯 节点选择",
		"DOMAIN-SUFFIX,cloudfront.net,🎯 节点选择",
		"DOMAIN-SUFFIX,ctitv.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,cuhk.edu.hk,🎯 节点选择",
		"DOMAIN-SUFFIX,cusu.hk,🎯 节点选择",
		"DOMAIN-SUFFIX,discord.gg,🎯 节点选择",
		"DOMAIN-SUFFIX,discuss.com.hk,🎯 节点选择",
		"DOMAIN-SUFFIX,dropboxapi.com,🎯 节点选择",
		"DOMAIN-SUFFIX,duolingo.cn,🎯 节点选择",
		"DOMAIN-SUFFIX,edditstatic.com,🎯 节点选择",
		"DOMAIN-SUFFIX,flickriver.com,🎯 节点选择",
		"DOMAIN-SUFFIX,focustaiwan.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,free.fr,🎯 节点选择",
		"DOMAIN-SUFFIX,gigacircle.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hk-pub.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hosting.co.uk,🎯 节点选择",
		"DOMAIN-SUFFIX,hwcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,ifixit.com,🎯 节点选择",
		"DOMAIN-SUFFIX,iphone4hongkong.com,🎯 节点选择",
		"DOMAIN-SUFFIX,iphonetaiwan.org,🎯 节点选择",
		"DOMAIN-SUFFIX,iptvbin.com,🎯 节点选择",
		"DOMAIN-SUFFIX,linksalpha.com,🎯 节点选择",
		"DOMAIN-SUFFIX,manyvids.com,🎯 节点选择",
		"DOMAIN-SUFFIX,myactimes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,newsblur.com,🎯 节点选择",
		"DOMAIN-SUFFIX,now.im,🎯 节点选择",
		"DOMAIN-SUFFIX,nowe.com,🎯 节点选择",
		"DOMAIN-SUFFIX,redditlist.com,🎯 节点选择",
		"DOMAIN-SUFFIX,s3.amazonaws.com,🎯 节点选择",
		"DOMAIN-SUFFIX,signal.org,🎯 节点选择",
		"DOMAIN-SUFFIX,smartmailcloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,sparknotes.com,🎯 节点选择",
		"DOMAIN-SUFFIX,streetvoice.com,🎯 节点选择",
		"DOMAIN-SUFFIX,supertop.co,🎯 节点选择",
		"DOMAIN-SUFFIX,tv.com,🎯 节点选择",
		"DOMAIN-SUFFIX,typepad.com,🎯 节点选择",
		"DOMAIN-SUFFIX,udnbkk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,urbanairship.com,🎯 节点选择",
		"DOMAIN-SUFFIX,whispersystems.org,🎯 节点选择",
		"DOMAIN-SUFFIX,wikia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,wolframalpha.com,🎯 节点选择",
		"DOMAIN-SUFFIX,x-art.com,🎯 节点选择",
		"DOMAIN-SUFFIX,yimg.com,🎯 节点选择",
		"DOMAIN,api.steampowered.com,🎯 节点选择",
		"DOMAIN,store.steampowered.com,🎯 节点选择",
		"DOMAIN-SUFFIX,aaplimg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apple.co,🎯 节点选择",
		"DOMAIN-SUFFIX,apple.com,🎯 节点选择",
		"DOMAIN-SUFFIX,apple-cloudkit.com,🎯 节点选择",
		"DOMAIN-SUFFIX,appstore.com,🎯 节点选择",
		"DOMAIN-SUFFIX,cdn-apple.com,🎯 节点选择",
		"DOMAIN-SUFFIX,crashlytics.com,🎯 节点选择",
		"DOMAIN-SUFFIX,icloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,icloud-content.com,🎯 节点选择",
		"DOMAIN-SUFFIX,me.com,🎯 节点选择",
		"DOMAIN-SUFFIX,mzstatic.com,🎯 节点选择",
		"DOMAIN,www-cdn.icloud.com.akadns.net,🎯 节点选择",
		"DOMAIN-SUFFIX,t.me,🎯 节点选择",
		"DOMAIN-SUFFIX,tdesktop.com,🎯 节点选择",
		"DOMAIN-SUFFIX,telegra.ph,🎯 节点选择",
		"DOMAIN-SUFFIX,telegram.me,🎯 节点选择",
		"DOMAIN-SUFFIX,telegram.org,🎯 节点选择",
		"IP-CIDR,91.108.4.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.8.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.12.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.16.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,91.108.56.0/22,🎯 节点选择,no-resolve",
		"IP-CIDR,149.154.160.0/20,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:b28:f23d::/48,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:b28:f23f::/48,🎯 节点选择,no-resolve",
		"IP-CIDR6,2001:67c:4e8::/48,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,googlevideo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,youtube.com,🎯 节点选择",
		"DOMAIN,youtubei.googleapis.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflix.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflix.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxext.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nflximg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nflximg.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxso.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxvideo.net,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest0.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest1.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest2.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest3.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest4.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest5.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest6.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest7.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest8.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest9.com,🎯 节点选择",
		"IP-CIDR,23.246.0.0/18,🎯 节点选择,no-resolve",
		"IP-CIDR,37.77.184.0/21,🎯 节点选择,no-resolve",
		"IP-CIDR,45.57.0.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,64.120.128.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,66.197.128.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,108.175.32.0/20,🎯 节点选择,no-resolve",
		"IP-CIDR,192.173.64.0/18,🎯 节点选择,no-resolve",
		"IP-CIDR,198.38.96.0/19,🎯 节点选择,no-resolve",
		"IP-CIDR,198.45.48.0/20,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,deezer.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dzcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,kkbox.com,🎯 节点选择",
		"DOMAIN-SUFFIX,kkbox.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,kfs.io,🎯 节点选择",
		"DOMAIN-SUFFIX,joox.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pandora.com,🎯 节点选择",
		"DOMAIN-SUFFIX,p-cdn.us,🎯 节点选择",
		"DOMAIN-SUFFIX,sndcdn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,soundcloud.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pscdn.co,🎯 节点选择",
		"DOMAIN-SUFFIX,scdn.co,🎯 节点选择",
		"DOMAIN-SUFFIX,spotify.com,🎯 节点选择",
		"DOMAIN-SUFFIX,spoti.fi,🎯 节点选择",
		"DOMAIN-KEYWORD,spotify.com,🎯 节点选择",
		"DOMAIN-KEYWORD,-spotify-com,🎯 节点选择",
		"DOMAIN-SUFFIX,tidal.com,🎯 节点选择",
		"DOMAIN-SUFFIX,c4assets.com,🎯 节点选择",
		"DOMAIN-SUFFIX,channel4.com,🎯 节点选择",
		"DOMAIN-SUFFIX,abema.io,🎯 节点选择",
		"DOMAIN-SUFFIX,ameba.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,abema.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,hayabusa.io,🎯 节点选择",
		"DOMAIN,abematv.akamaized.net,🎯 节点选择",
		"DOMAIN,ds-linear-abematv.akamaized.net,🎯 节点选择",
		"DOMAIN,ds-vod-abematv.akamaized.net,🎯 节点选择",
		"DOMAIN,linear-abematv.akamaized.net,🎯 节点选择",
		"DOMAIN-SUFFIX,aiv-cdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,aiv-delivery.net,🎯 节点选择",
		"DOMAIN-SUFFIX,amazonvideo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,primevideo.com,🎯 节点选择",
		"DOMAIN,avodmp4s3ww-a.akamaihd.net,🎯 节点选择",
		"DOMAIN,d25xi40x97liuc.cloudfront.net,🎯 节点选择",
		"DOMAIN,dmqdd6hw24ucf.cloudfront.net,🎯 节点选择",
		"DOMAIN,d22qjgkvxw22r6.cloudfront.net,🎯 节点选择",
		"DOMAIN,d1v5ir2lpwr8os.cloudfront.net,🎯 节点选择",
		"DOMAIN-KEYWORD,avoddashs,🎯 节点选择",
		"DOMAIN-SUFFIX,bahamut.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,gamer.com.tw,🎯 节点选择",
		"DOMAIN,gamer-cds.cdn.hinet.net,🎯 节点选择",
		"DOMAIN,gamer2-cds.cdn.hinet.net,🎯 节点选择",
		"DOMAIN-SUFFIX,bbc.co.uk,🎯 节点选择",
		"DOMAIN-SUFFIX,bbci.co.uk,🎯 节点选择",
		"DOMAIN-KEYWORD,bbcfmt,🎯 节点选择",
		"DOMAIN-KEYWORD,uk-live,🎯 节点选择",
		"DOMAIN-SUFFIX,dazn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dazn-api.com,🎯 节点选择",
		"DOMAIN,d151l6v8er5bdm.cloudfront.net,🎯 节点选择",
		"DOMAIN-KEYWORD,voddazn,🎯 节点选择",
		"DOMAIN-SUFFIX,bamgrid.com,🎯 节点选择",
		"DOMAIN-SUFFIX,disney-plus.net,🎯 节点选择",
		"DOMAIN-SUFFIX,disneyplus.com,🎯 节点选择",
		"DOMAIN-SUFFIX,dssott.com,🎯 节点选择",
		"DOMAIN,cdn.registerdisney.go.com,🎯 节点选择",
		"DOMAIN-SUFFIX,encoretvb.com,🎯 节点选择",
		"DOMAIN,edge.api.brightcove.com,🎯 节点选择",
		"DOMAIN,bcbolt446c5271-a.akamaihd.net,🎯 节点选择",
		"DOMAIN-SUFFIX,fox.com,🎯 节点选择",
		"DOMAIN-SUFFIX,foxdcg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,theplatform.com,🎯 节点选择",
		"DOMAIN-SUFFIX,uplynk.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbogo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbonow.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbogoasia.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hbogoasia.hk,🎯 节点选择",
		"DOMAIN,bcbolthboa-a.akamaihd.net,🎯 节点选择",
		"DOMAIN,players.brightcove.net,🎯 节点选择",
		"DOMAIN,s3-ap-southeast-1.amazonaws.com,🎯 节点选择",
		"DOMAIN,dai3fd1oh325y.cloudfront.net,🎯 节点选择",
		"DOMAIN,44wilhpljf.execute-api.ap-southeast-1.amazonaws.com,🎯 节点选择",
		"DOMAIN,hboasia1-i.akamaihd.net,🎯 节点选择",
		"DOMAIN,hboasia2-i.akamaihd.net,🎯 节点选择",
		"DOMAIN,hboasia3-i.akamaihd.net,🎯 节点选择",
		"DOMAIN,hboasia4-i.akamaihd.net,🎯 节点选择",
		"DOMAIN,hboasia5-i.akamaihd.net,🎯 节点选择",
		"DOMAIN,cf-images.ap-southeast-1.prod.boltdns.net,🎯 节点选择",
		"DOMAIN-SUFFIX,5itv.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,ocnttv.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hulu.com,🎯 节点选择",
		"DOMAIN-SUFFIX,huluim.com,🎯 节点选择",
		"DOMAIN-SUFFIX,hulustream.com,🎯 节点选择",
		"DOMAIN-SUFFIX,happyon.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,hulu.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,itv.com,🎯 节点选择",
		"DOMAIN-SUFFIX,itvstatic.com,🎯 节点选择",
		"DOMAIN,itvpnpmobile-a.akamaihd.net,🎯 节点选择",
		"DOMAIN-SUFFIX,kktv.com.tw,🎯 节点选择",
		"DOMAIN-SUFFIX,kktv.me,🎯 节点选择",
		"DOMAIN,kktv-theater.kk.stream,🎯 节点选择",
		"DOMAIN-SUFFIX,linetv.tw,🎯 节点选择",
		"DOMAIN,d3c7rimkq79yfu.cloudfront.net,🎯 节点选择",
		"DOMAIN-SUFFIX,litv.tv,🎯 节点选择",
		"DOMAIN,litvfreemobile-hichannel.cdn.hinet.net,🎯 节点选择",
		"DOMAIN-SUFFIX,channel5.com,🎯 节点选择",
		"DOMAIN-SUFFIX,my5.tv,🎯 节点选择",
		"DOMAIN,d349g9zuie06uo.cloudfront.net,🎯 节点选择",
		"DOMAIN-SUFFIX,mytvsuper.com,🎯 节点选择",
		"DOMAIN-SUFFIX,tvb.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflix.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflix.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxext.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nflximg.com,🎯 节点选择",
		"DOMAIN-SUFFIX,nflximg.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxso.net,🎯 节点选择",
		"DOMAIN-SUFFIX,nflxvideo.net,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest0.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest1.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest2.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest3.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest4.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest5.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest6.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest7.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest8.com,🎯 节点选择",
		"DOMAIN-SUFFIX,netflixdnstest9.com,🎯 节点选择",
		"IP-CIDR,23.246.0.0/18,🎯 节点选择,no-resolve",
		"IP-CIDR,37.77.184.0/21,🎯 节点选择,no-resolve",
		"IP-CIDR,45.57.0.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,64.120.128.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,66.197.128.0/17,🎯 节点选择,no-resolve",
		"IP-CIDR,108.175.32.0/20,🎯 节点选择,no-resolve",
		"IP-CIDR,192.173.64.0/18,🎯 节点选择,no-resolve",
		"IP-CIDR,198.38.96.0/19,🎯 节点选择,no-resolve",
		"IP-CIDR,198.45.48.0/20,🎯 节点选择,no-resolve",
		"DOMAIN-SUFFIX,dmc.nico,🎯 节点选择",
		"DOMAIN-SUFFIX,nicovideo.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,nimg.jp,🎯 节点选择",
		"DOMAIN-SUFFIX,socdm.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pbs.org,🎯 节点选择",
		"DOMAIN-SUFFIX,phncdn.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pornhub.com,🎯 节点选择",
		"DOMAIN-SUFFIX,pornhubpremium.com,🎯 节点选择",
		"DOMAIN-SUFFIX,skyking.com.tw,🎯 节点选择",
		"DOMAIN,hamifans.emome.net,🎯 节点选择",
		"DOMAIN-SUFFIX,twitch.tv,🎯 节点选择",
		"DOMAIN-SUFFIX,twitchcdn.net,🎯 节点选择",
		"DOMAIN-SUFFIX,ttvnw.net,🎯 节点选择",
		"DOMAIN-SUFFIX,jtvnw.net,🎯 节点选择",
		"DOMAIN-SUFFIX,viu.com,🎯 节点选择",
		"DOMAIN-SUFFIX,viu.tv,🎯 节点选择",
		"DOMAIN,api.viu.now.com,🎯 节点选择",
		"DOMAIN,d1k2us671qcoau.cloudfront.net,🎯 节点选择",
		"DOMAIN,d2anahhhmp1ffz.cloudfront.net,🎯 节点选择",
		"DOMAIN,dfp6rglgjqszk.cloudfront.net,🎯 节点选择",
		"DOMAIN-SUFFIX,googlevideo.com,🎯 节点选择",
		"DOMAIN-SUFFIX,youtube.com,🎯 节点选择",
		"DOMAIN,youtubei.googleapis.com,🎯 节点选择",
		"DOMAIN-SUFFIX,local,DIRECT",
		"IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
		"IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
		"IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
		"IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
		"IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
		"IP-CIDR6,::1/128,DIRECT,no-resolve",
		"IP-CIDR6,fc00::/7,DIRECT,no-resolve",
		"IP-CIDR6,fe80::/10,DIRECT,no-resolve",
		"IP-CIDR6,fd00::/8,DIRECT,no-resolve",
		"DOMAIN,app.adjust.com,DIRECT",
		"DOMAIN-SUFFIX,googletraveladservices.com,DIRECT",
		"DOMAIN,dl.google.com,DIRECT",
		"DOMAIN,mtalk.google.com,DIRECT",
		"DOMAIN,livew.l.qq.com,DIRECT",
		"DOMAIN,vd.l.qq.com,DIRECT",
		"DOMAIN,analytics.strava.com,DIRECT",
		"DOMAIN,msg.umeng.com,DIRECT",
		"DOMAIN,msg.umengcloud.com,DIRECT",
		"DOMAIN-SUFFIX,qhres.com,DIRECT",
		"DOMAIN-SUFFIX,qhimg.com,DIRECT",
		"DOMAIN-SUFFIX,akadns.net,DIRECT",
		"DOMAIN-SUFFIX,alibaba.com,DIRECT",
		"DOMAIN-SUFFIX,alicdn.com,DIRECT",
		"DOMAIN-SUFFIX,alikunlun.com,DIRECT",
		"DOMAIN-SUFFIX,alipay.com,DIRECT",
		"DOMAIN-SUFFIX,amap.com,DIRECT",
		"DOMAIN-SUFFIX,autonavi.com,DIRECT",
		"DOMAIN-SUFFIX,dingtalk.com,DIRECT",
		"DOMAIN-SUFFIX,mxhichina.com,DIRECT",
		"DOMAIN-SUFFIX,soku.com,DIRECT",
		"DOMAIN-SUFFIX,taobao.com,DIRECT",
		"DOMAIN-SUFFIX,tmall.com,DIRECT",
		"DOMAIN-SUFFIX,tmall.hk,DIRECT",
		"DOMAIN-SUFFIX,ykimg.com,DIRECT",
		"DOMAIN-SUFFIX,youku.com,DIRECT",
		"DOMAIN-SUFFIX,xiami.com,DIRECT",
		"DOMAIN-SUFFIX,xiami.net,DIRECT",
		"DOMAIN-SUFFIX,aaplimg.com,DIRECT",
		"DOMAIN-SUFFIX,apple.co,DIRECT",
		"DOMAIN-SUFFIX,apple.com,DIRECT",
		"DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT",
		"DOMAIN-SUFFIX,appstore.com,DIRECT",
		"DOMAIN-SUFFIX,cdn-apple.com,DIRECT",
		"DOMAIN-SUFFIX,crashlytics.com,DIRECT",
		"DOMAIN-SUFFIX,icloud.com,DIRECT",
		"DOMAIN-SUFFIX,icloud-content.com,DIRECT",
		"DOMAIN-SUFFIX,me.com,DIRECT",
		"DOMAIN-SUFFIX,mzstatic.com,DIRECT",
		"DOMAIN,www-cdn.icloud.com.akadns.net,DIRECT",
		"DOMAIN-SUFFIX,baidu.com,DIRECT",
		"DOMAIN-SUFFIX,baidubcr.com,DIRECT",
		"DOMAIN-SUFFIX,bdstatic.com,DIRECT",
		"DOMAIN-SUFFIX,yunjiasu-cdn.net,DIRECT",
		"DOMAIN-SUFFIX,acgvideo.com,DIRECT",
		"DOMAIN-SUFFIX,biliapi.com,DIRECT",
		"DOMAIN-SUFFIX,biliapi.net,DIRECT",
		"DOMAIN-SUFFIX,bilibili.com,DIRECT",
		"DOMAIN-SUFFIX,bilibili.tv,DIRECT",
		"DOMAIN-SUFFIX,bilivideo.com,DIRECT",
		"DOMAIN-SUFFIX,hdslb.com,DIRECT",
		"DOMAIN-SUFFIX,blizzard.com,DIRECT",
		"DOMAIN-SUFFIX,battle.net,DIRECT",
		"DOMAIN,blzddist1-a.akamaihd.net,DIRECT",
		"DOMAIN-SUFFIX,feiliao.com,DIRECT",
		"DOMAIN-SUFFIX,pstatp.com,DIRECT",
		"DOMAIN-SUFFIX,snssdk.com,DIRECT",
		"DOMAIN-SUFFIX,iesdouyin.com,DIRECT",
		"DOMAIN-SUFFIX,toutiao.com,DIRECT",
		"DOMAIN-SUFFIX,cctv.com,DIRECT",
		"DOMAIN-SUFFIX,cctvpic.com,DIRECT",
		"DOMAIN-SUFFIX,livechina.com,DIRECT",
		"DOMAIN-SUFFIX,didialift.com,DIRECT",
		"DOMAIN-SUFFIX,didiglobal.com,DIRECT",
		"DOMAIN-SUFFIX,udache.com,DIRECT",
		"DOMAIN-SUFFIX,343480.com,DIRECT",
		"DOMAIN-SUFFIX,baduziyuan.com,DIRECT",
		"DOMAIN-SUFFIX,com-hs-hkdy.com,DIRECT",
		"DOMAIN-SUFFIX,czybjz.com,DIRECT",
		"DOMAIN-SUFFIX,dandanzan.com,DIRECT",
		"DOMAIN-SUFFIX,fjhps.com,DIRECT",
		"DOMAIN-SUFFIX,kuyunbo.club,DIRECT",
		"DOMAIN-SUFFIX,21cn.com,DIRECT",
		"DOMAIN-SUFFIX,hitv.com,DIRECT",
		"DOMAIN-SUFFIX,mgtv.com,DIRECT",
		"DOMAIN-SUFFIX,iqiyi.com,DIRECT",
		"DOMAIN-SUFFIX,iqiyipic.com,DIRECT",
		"DOMAIN-SUFFIX,71.am.com,DIRECT",
		"DOMAIN-SUFFIX,jd.com,DIRECT",
		"DOMAIN-SUFFIX,jd.hk,DIRECT",
		"DOMAIN-SUFFIX,jdpay.com,DIRECT",
		"DOMAIN-SUFFIX,360buyimg.com,DIRECT",
		"DOMAIN-SUFFIX,iciba.com,DIRECT",
		"DOMAIN-SUFFIX,ksosoft.com,DIRECT",
		"DOMAIN-SUFFIX,meitu.com,DIRECT",
		"DOMAIN-SUFFIX,meitudata.com,DIRECT",
		"DOMAIN-SUFFIX,meitustat.com,DIRECT",
		"DOMAIN-SUFFIX,meipai.com,DIRECT",
		"DOMAIN-SUFFIX,duokan.com,DIRECT",
		"DOMAIN-SUFFIX,mi-img.com,DIRECT",
		"DOMAIN-SUFFIX,miui.com,DIRECT",
		"DOMAIN-SUFFIX,miwifi.com,DIRECT",
		"DOMAIN-SUFFIX,xiaomi.com,DIRECT",
		"DOMAIN-SUFFIX,microsoft.com,DIRECT",
		"DOMAIN-SUFFIX,msecnd.net,DIRECT",
		"DOMAIN-SUFFIX,office365.com,DIRECT",
		"DOMAIN-SUFFIX,outlook.com,DIRECT",
		"DOMAIN-SUFFIX,s-microsoft.com,DIRECT",
		"DOMAIN-SUFFIX,visualstudio.com,DIRECT",
		"DOMAIN-SUFFIX,windows.com,DIRECT",
		"DOMAIN-SUFFIX,windowsupdate.com,DIRECT",
		"DOMAIN,officecdn-microsoft-com.akamaized.net,DIRECT",
		"DOMAIN-SUFFIX,163.com,DIRECT",
		"DOMAIN-SUFFIX,126.net,DIRECT",
		"DOMAIN-SUFFIX,127.net,DIRECT",
		"DOMAIN-SUFFIX,163yun.com,DIRECT",
		"DOMAIN-SUFFIX,lofter.com,DIRECT",
		"DOMAIN-SUFFIX,netease.com,DIRECT",
		"DOMAIN-SUFFIX,ydstatic.com,DIRECT",
		"DOMAIN-SUFFIX,sina.com,DIRECT",
		"DOMAIN-SUFFIX,weibo.com,DIRECT",
		"DOMAIN-SUFFIX,weibocdn.com,DIRECT",
		"DOMAIN-SUFFIX,sohu.com,DIRECT",
		"DOMAIN-SUFFIX,sohucs.com,DIRECT",
		"DOMAIN-SUFFIX,sohu-inc.com,DIRECT",
		"DOMAIN-SUFFIX,v-56.com,DIRECT",
		"DOMAIN-SUFFIX,sogo.com,DIRECT",
		"DOMAIN-SUFFIX,sogou.com,DIRECT",
		"DOMAIN-SUFFIX,sogoucdn.com,DIRECT",
		"DOMAIN-SUFFIX,steampowered.com,DIRECT",
		"DOMAIN-SUFFIX,steam-chat.com,DIRECT",
		"DOMAIN-SUFFIX,steamgames.com,DIRECT",
		"DOMAIN-SUFFIX,steamusercontent.com,DIRECT",
		"DOMAIN-SUFFIX,steamcontent.com,DIRECT",
		"DOMAIN-SUFFIX,steamstatic.com,DIRECT",
		"DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,DIRECT",
		"DOMAIN-SUFFIX,steamstat.us,DIRECT",
		"DOMAIN-SUFFIX,gtimg.com,DIRECT",
		"DOMAIN-SUFFIX,idqqimg.com,DIRECT",
		"DOMAIN-SUFFIX,igamecj.com,DIRECT",
		"DOMAIN-SUFFIX,myapp.com,DIRECT",
		"DOMAIN-SUFFIX,myqcloud.com,DIRECT",
		"DOMAIN-SUFFIX,qq.com,DIRECT",
		"DOMAIN-SUFFIX,tencent.com,DIRECT",
		"DOMAIN-SUFFIX,tencent-cloud.net,DIRECT",
		"DOMAIN-SUFFIX,jstucdn.com,DIRECT",
		"DOMAIN-SUFFIX,zimuzu.io,DIRECT",
		"DOMAIN-SUFFIX,zimuzu.tv,DIRECT",
		"DOMAIN-SUFFIX,zmz2019.com,DIRECT",
		"DOMAIN-SUFFIX,zmzapi.com,DIRECT",
		"DOMAIN-SUFFIX,zmzapi.net,DIRECT",
		"DOMAIN-SUFFIX,zmzfile.com,DIRECT",
		"DOMAIN-SUFFIX,ccgslb.com,DIRECT",
		"DOMAIN-SUFFIX,ccgslb.net,DIRECT",
		"DOMAIN-SUFFIX,chinanetcenter.com,DIRECT",
		"DOMAIN-SUFFIX,meixincdn.com,DIRECT",
		"DOMAIN-SUFFIX,ourdvs.com,DIRECT",
		"DOMAIN-SUFFIX,staticdn.net,DIRECT",
		"DOMAIN-SUFFIX,wangsu.com,DIRECT",
		"DOMAIN-SUFFIX,ipip.net,DIRECT",
		"DOMAIN-SUFFIX,ip.la,DIRECT",
		"DOMAIN-SUFFIX,ip-cdn.com,DIRECT",
		"DOMAIN-SUFFIX,ipv6-test.com,DIRECT",
		"DOMAIN-SUFFIX,test-ipv6.com,DIRECT",
		"DOMAIN-SUFFIX,whatismyip.com,DIRECT",
		"DOMAIN-SUFFIX,netspeedtestmaster.com,DIRECT",
		"DOMAIN,speedtest.macpaw.com,DIRECT",
		"DOMAIN-SUFFIX,awesome-hd.me,DIRECT",
		"DOMAIN-SUFFIX,broadcasthe.net,DIRECT",
		"DOMAIN-SUFFIX,chdbits.co,DIRECT",
		"DOMAIN-SUFFIX,classix-unlimited.co.uk,DIRECT",
		"DOMAIN-SUFFIX,empornium.me,DIRECT",
		"DOMAIN-SUFFIX,gazellegames.net,DIRECT",
		"DOMAIN-SUFFIX,hdchina.org,DIRECT",
		"DOMAIN-SUFFIX,hdsky.me,DIRECT",
		"DOMAIN-SUFFIX,icetorrent.org,DIRECT",
		"DOMAIN-SUFFIX,jpopsuki.eu,DIRECT",
		"DOMAIN-SUFFIX,keepfrds.com,DIRECT",
		"DOMAIN-SUFFIX,madsrevolution.net,DIRECT",
		"DOMAIN-SUFFIX,m-team.cc,DIRECT",
		"DOMAIN-SUFFIX,nanyangpt.com,DIRECT",
		"DOMAIN-SUFFIX,ncore.cc,DIRECT",
		"DOMAIN-SUFFIX,open.cd,DIRECT",
		"DOMAIN-SUFFIX,ourbits.club,DIRECT",
		"DOMAIN-SUFFIX,passthepopcorn.me,DIRECT",
		"DOMAIN-SUFFIX,privatehd.to,DIRECT",
		"DOMAIN-SUFFIX,redacted.ch,DIRECT",
		"DOMAIN-SUFFIX,springsunday.net,DIRECT",
		"DOMAIN-SUFFIX,tjupt.org,DIRECT",
		"DOMAIN-SUFFIX,totheglory.im,DIRECT",
		"DOMAIN-SUFFIX,acm.org,DIRECT",
		"DOMAIN-SUFFIX,acs.org,DIRECT",
		"DOMAIN-SUFFIX,aip.org,DIRECT",
		"DOMAIN-SUFFIX,ams.org,DIRECT",
		"DOMAIN-SUFFIX,annualreviews.org,DIRECT",
		"DOMAIN-SUFFIX,aps.org,DIRECT",
		"DOMAIN-SUFFIX,ascelibrary.org,DIRECT",
		"DOMAIN-SUFFIX,asm.org,DIRECT",
		"DOMAIN-SUFFIX,asme.org,DIRECT",
		"DOMAIN-SUFFIX,astm.org,DIRECT",
		"DOMAIN-SUFFIX,bmj.com,DIRECT",
		"DOMAIN-SUFFIX,cambridge.org,DIRECT",
		"DOMAIN-SUFFIX,cas.org,DIRECT",
		"DOMAIN-SUFFIX,clarivate.com,DIRECT",
		"DOMAIN-SUFFIX,ebscohost.com,DIRECT",
		"DOMAIN-SUFFIX,emerald.com,DIRECT",
		"DOMAIN-SUFFIX,engineeringvillage.com,DIRECT",
		"DOMAIN-SUFFIX,icevirtuallibrary.com,DIRECT",
		"DOMAIN-SUFFIX,ieee.org,DIRECT",
		"DOMAIN-SUFFIX,imf.org,DIRECT",
		"DOMAIN-SUFFIX,iop.org,DIRECT",
		"DOMAIN-SUFFIX,jamanetwork.com,DIRECT",
		"DOMAIN-SUFFIX,jhu.edu,DIRECT",
		"DOMAIN-SUFFIX,jstor.org,DIRECT",
		"DOMAIN-SUFFIX,karger.com,DIRECT",
		"DOMAIN-SUFFIX,libguides.com,DIRECT",
		"DOMAIN-SUFFIX,madsrevolution.net,DIRECT",
		"DOMAIN-SUFFIX,mpg.de,DIRECT",
		"DOMAIN-SUFFIX,myilibrary.com,DIRECT",
		"DOMAIN-SUFFIX,nature.com,DIRECT",
		"DOMAIN-SUFFIX,oecd-ilibrary.org,DIRECT",
		"DOMAIN-SUFFIX,osapublishing.org,DIRECT",
		"DOMAIN-SUFFIX,oup.com,DIRECT",
		"DOMAIN-SUFFIX,ovid.com,DIRECT",
		"DOMAIN-SUFFIX,oxfordartonline.com,DIRECT",
		"DOMAIN-SUFFIX,oxfordbibliographies.com,DIRECT",
		"DOMAIN-SUFFIX,oxfordmusiconline.com,DIRECT",
		"DOMAIN-SUFFIX,pnas.org,DIRECT",
		"DOMAIN-SUFFIX,proquest.com,DIRECT",
		"DOMAIN-SUFFIX,rsc.org,DIRECT",
		"DOMAIN-SUFFIX,sagepub.com,DIRECT",
		"DOMAIN-SUFFIX,sciencedirect.com,DIRECT",
		"DOMAIN-SUFFIX,sciencemag.org,DIRECT",
		"DOMAIN-SUFFIX,scopus.com,DIRECT",
		"DOMAIN-SUFFIX,siam.org,DIRECT",
		"DOMAIN-SUFFIX,spiedigitallibrary.org,DIRECT",
		"DOMAIN-SUFFIX,springer.com,DIRECT",
		"DOMAIN-SUFFIX,springerlink.com,DIRECT",
		"DOMAIN-SUFFIX,tandfonline.com,DIRECT",
		"DOMAIN-SUFFIX,un.org,DIRECT",
		"DOMAIN-SUFFIX,uni-bielefeld.de,DIRECT",
		"DOMAIN-SUFFIX,webofknowledge.com,DIRECT",
		"DOMAIN-SUFFIX,westlaw.com,DIRECT",
		"DOMAIN-SUFFIX,wiley.com,DIRECT",
		"DOMAIN-SUFFIX,worldbank.org,DIRECT",
		"DOMAIN-SUFFIX,worldscientific.com,DIRECT",
		"DOMAIN-SUFFIX,cn,DIRECT",
		"DOMAIN-SUFFIX,360in.com,DIRECT",
		"DOMAIN-SUFFIX,51ym.me,DIRECT",
		"DOMAIN-SUFFIX,8686c.com,DIRECT",
		"DOMAIN-SUFFIX,abchina.com,DIRECT",
		"DOMAIN-SUFFIX,accuweather.com,DIRECT",
		"DOMAIN-SUFFIX,aicoinstorge.com,DIRECT",
		"DOMAIN-SUFFIX,air-matters.com,DIRECT",
		"DOMAIN-SUFFIX,air-matters.io,DIRECT",
		"DOMAIN-SUFFIX,aixifan.com,DIRECT",
		"DOMAIN-SUFFIX,amd.com,DIRECT",
		"DOMAIN-SUFFIX,b612.net,DIRECT",
		"DOMAIN-SUFFIX,bdatu.com,DIRECT",
		"DOMAIN-SUFFIX,beitaichufang.com,DIRECT",
		"DOMAIN-SUFFIX,bjango.com,DIRECT",
		"DOMAIN-SUFFIX,booking.com,DIRECT",
		"DOMAIN-SUFFIX,bstatic.com,DIRECT",
		"DOMAIN-SUFFIX,cailianpress.com,DIRECT",
		"DOMAIN-SUFFIX,camera360.com,DIRECT",
		"DOMAIN-SUFFIX,chinaso.com,DIRECT",
		"DOMAIN-SUFFIX,chua.pro,DIRECT",
		"DOMAIN-SUFFIX,chuimg.com,DIRECT",
		"DOMAIN-SUFFIX,chunyu.mobi,DIRECT",
		"DOMAIN-SUFFIX,chushou.tv,DIRECT",
		"DOMAIN-SUFFIX,cmbchina.com,DIRECT",
		"DOMAIN-SUFFIX,cmbimg.com,DIRECT",
		"DOMAIN-SUFFIX,ctrip.com,DIRECT",
		"DOMAIN-SUFFIX,dfcfw.com,DIRECT",
		"DOMAIN-SUFFIX,docschina.org,DIRECT",
		"DOMAIN-SUFFIX,douban.com,DIRECT",
		"DOMAIN-SUFFIX,doubanio.com,DIRECT",
		"DOMAIN-SUFFIX,douyu.com,DIRECT",
		"DOMAIN-SUFFIX,dxycdn.com,DIRECT",
		"DOMAIN-SUFFIX,dytt8.net,DIRECT",
		"DOMAIN-SUFFIX,eastmoney.com,DIRECT",
		"DOMAIN-SUFFIX,eudic.net,DIRECT",
		"DOMAIN-SUFFIX,feng.com,DIRECT",
		"DOMAIN-SUFFIX,fengkongcloud.com,DIRECT",
		"DOMAIN-SUFFIX,frdic.com,DIRECT",
		"DOMAIN-SUFFIX,futu5.com,DIRECT",
		"DOMAIN-SUFFIX,futunn.com,DIRECT",
		"DOMAIN-SUFFIX,gandi.net,DIRECT",
		"DOMAIN-SUFFIX,geilicdn.com,DIRECT",
		"DOMAIN-SUFFIX,getpricetag.com,DIRECT",
		"DOMAIN-SUFFIX,gifshow.com,DIRECT",
		"DOMAIN-SUFFIX,godic.net,DIRECT",
		"DOMAIN-SUFFIX,hicloud.com,DIRECT",
		"DOMAIN-SUFFIX,hongxiu.com,DIRECT",
		"DOMAIN-SUFFIX,hostbuf.com,DIRECT",
		"DOMAIN-SUFFIX,huxiucdn.com,DIRECT",
		"DOMAIN-SUFFIX,huya.com,DIRECT",
		"DOMAIN-SUFFIX,infinitynewtab.com,DIRECT",
		"DOMAIN-SUFFIX,ithome.com,DIRECT",
		"DOMAIN-SUFFIX,java.com,DIRECT",
		"DOMAIN-SUFFIX,jidian.im,DIRECT",
		"DOMAIN-SUFFIX,kaiyanapp.com,DIRECT",
		"DOMAIN-SUFFIX,kaspersky-labs.com,DIRECT",
		"DOMAIN-SUFFIX,keepcdn.com,DIRECT",
		"DOMAIN-SUFFIX,kkmh.com,DIRECT",
		"DOMAIN-SUFFIX,licdn.com,DIRECT",
		"DOMAIN-SUFFIX,loli.net,DIRECT",
		"DOMAIN-SUFFIX,luojilab.com,DIRECT",
		"DOMAIN-SUFFIX,maoyan.com,DIRECT",
		"DOMAIN-SUFFIX,maoyun.tv,DIRECT",
		"DOMAIN-SUFFIX,meituan.com,DIRECT",
		"DOMAIN-SUFFIX,meituan.net,DIRECT",
		"DOMAIN-SUFFIX,mobike.com,DIRECT",
		"DOMAIN-SUFFIX,moke.com,DIRECT",
		"DOMAIN-SUFFIX,mubu.com,DIRECT",
		"DOMAIN-SUFFIX,myzaker.com,DIRECT",
		"DOMAIN-SUFFIX,nim-lang-cn.org,DIRECT",
		"DOMAIN-SUFFIX,nvidia.com,DIRECT",
		"DOMAIN-SUFFIX,oracle.com,DIRECT",
		"DOMAIN-SUFFIX,paypal.com,DIRECT",
		"DOMAIN-SUFFIX,paypalobjects.com,DIRECT",
		"DOMAIN-SUFFIX,qdaily.com,DIRECT",
		"DOMAIN-SUFFIX,qidian.com,DIRECT",
		"DOMAIN-SUFFIX,qyer.com,DIRECT",
		"DOMAIN-SUFFIX,qyerstatic.com,DIRECT",
		"DOMAIN-SUFFIX,raychase.net,DIRECT",
		"DOMAIN-SUFFIX,ronghub.com,DIRECT",
		"DOMAIN-SUFFIX,ruguoapp.com,DIRECT",
		"DOMAIN-SUFFIX,s-reader.com,DIRECT",
		"DOMAIN-SUFFIX,sankuai.com,DIRECT",
		"DOMAIN-SUFFIX,scomper.me,DIRECT",
		"DOMAIN-SUFFIX,seafile.com,DIRECT",
		"DOMAIN-SUFFIX,sm.ms,DIRECT",
		"DOMAIN-SUFFIX,smzdm.com,DIRECT",
		"DOMAIN-SUFFIX,snapdrop.net,DIRECT",
		"DOMAIN-SUFFIX,snwx.com,DIRECT",
		"DOMAIN-SUFFIX,sspai.com,DIRECT",
		"DOMAIN-SUFFIX,takungpao.com,DIRECT",
		"DOMAIN-SUFFIX,teamviewer.com,DIRECT",
		"DOMAIN-SUFFIX,tianyancha.com,DIRECT",
		"DOMAIN-SUFFIX,udacity.com,DIRECT",
		"DOMAIN-SUFFIX,uning.com,DIRECT",
		"DOMAIN-SUFFIX,vmware.com,DIRECT",
		"DOMAIN-SUFFIX,weather.com,DIRECT",
		"DOMAIN-SUFFIX,weico.cc,DIRECT",
		"DOMAIN-SUFFIX,weidian.com,DIRECT",
		"DOMAIN-SUFFIX,xiachufang.com,DIRECT",
		"DOMAIN-SUFFIX,ximalaya.com,DIRECT",
		"DOMAIN-SUFFIX,xinhuanet.com,DIRECT",
		"DOMAIN-SUFFIX,xmcdn.com,DIRECT",
		"DOMAIN-SUFFIX,yangkeduo.com,DIRECT",
		"DOMAIN-SUFFIX,zhangzishi.cc,DIRECT",
		"DOMAIN-SUFFIX,zhihu.com,DIRECT",
		"DOMAIN-SUFFIX,zhimg.com,DIRECT",
		"DOMAIN-SUFFIX,zhuihd.com,DIRECT",
		"DOMAIN-SUFFIX,balala.work,DIRECT",
		"DOMAIN-SUFFIX,balala.top,DIRECT",
		"DOMAIN,download.jetbrains.com,DIRECT",
		"DOMAIN,images-cn.ssl-images-amazon.com,DIRECT",
		"IP-CIDR,119.28.28.28/32,DIRECT,no-resolve",
		"GEOIP,CN,DIRECT",
		"MATCH,🎯 节点选择"
	],
	'allow-lan': false,
	'external-controller': '127.0.0.1:9090',
	'log-level': 'info',
	mode: 'Rule',
	port: 7890,
	'socks-port': 7891,
	dns: {
		enable: true,
		//listen: '127.0.0.1:53',
		'default-nameserver': ['223.5.5.5', '119.29.29.29'],
		ipv6: false,
		'enhanced-mode': 'fake-ip',
		'fake-ip-range': '198.10.0.1/16',
		nameserver: ['119.29.29.29', '223.5.5.5', 'https://dns.alidns.com/dns-query']
	}
};
